name: TMDB_Test
description: Projeto feito para teste de algumas animações
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tmdb_api: ^1.2.5
  transparent_image: ^1.0.0
  cached_network_image: ^2.5.0
  google_fonts: ^1.1.1
  intl: ^0.16.1
  simple_animations:


  ## MobX
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  get_it: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.12
  mobx_codegen: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/